-- plugins/which-key.lua
return {
  "folke/which-key.nvim",
  config = function()
    local wk = require("which-key")
    wk.setup {
      plugins = {
        spelling = {
          enabled = true,
        },
      },
      ignore_missing = true,
    }

		  {
    { "<leader>CP", desc = ":CCCCONVERT<CR>" },
    { "<leader>CR", desc = ":RELOADCONFIG<CR>" },
    { "<leader>a", group = " AI" },
    { "<leader>aC", desc = ":AvanteClear<CR>" },
    { "<leader>am", desc = ":MCPHub<CR>" },
    { "<leader>an", desc = ":AvanteChatNew<CR>" },
    { "<leader>ap", group = "Insert Prompt" },
    { "<leader>apd", desc = "<cmd>lua require('lib.prompts').add_prompt('docs')<CR>" },
    { "<leader>ape", desc = "<cmd>lua require('lib.prompts').add_prompt('explain')<CR>" },
    { "<leader>apf", desc = "<cmd>lua require('lib.prompts').add_prompt('fix')<CR>" },
    { "<leader>apg", desc = "<cmd>lua require('lib.prompts').add_prompt('commit')<CR>" },
    { "<leader>apo", desc = "<cmd>lua require('lib.prompts').add_prompt('optimize')<CR>" },
    { "<leader>apr", desc = "<cmd>lua require('lib.prompts').add_prompt('review')<CR>" },
    { "<leader>apt", desc = "<cmd>lua require('lib.prompts').add_prompt('tests')<CR>" },
    { "<leader>c", group = " Code" },
    { "<leader>cF", desc = ":retab<CR>" },
    { "<leader>cc", desc = ":CccHighlighterToggle<CR>" },
    { "<leader>cd", desc = ":RootDir<CR>" },
    { "<leader>ce", desc = ":%SnipRun<CR>" },
    { "<leader>cf", desc = ":lua vim.lsp.buf.format({async = true})<CR>" },
    { "<leader>cl", desc = "::g/\\s*$/d<CR>" },
    { "<leader>cm", desc = ":MarkdownPreviewToggle<CR>" },
    { "<leader>co", desc = ":Dashboard<CR>" },
    { "<leader>cp", desc = ":CccPick<CR>" },
    { "<leader>cs", desc = ":source %<CR>" },
    { "<leader>e", group = " Edit" },
    { "<leader>eE", desc = ":NvimTreeToggle<CR>" },
    { "<leader>ea", desc = ":b#<CR>" },
    { "<leader>ec", group = "Edit Configs" },
    { "<leader>ef", desc = "gf" },
    { "<leader>em", desc = ":e README.md<CR>" },
    { "<leader>en", desc = ":enew<CR>" },
    { "<leader>et", desc = ":NvimTreeFindFile<CR>" },
    { "<leader>f", group = " Find" },
    { "<leader>fb", desc = "<cmd>Telescope buffers<CR>" },
    { "<leader>ff", desc = "<cmd>Telescope find_files<CR>" },
    { "<leader>fg", desc = "<cmd>Telescope live_grep<CR>" },
    { "<leader>fh", desc = "<cmd>Telescope help_tags<CR>" },
    { "<leader>fx", desc = ":%bd|e#|bd#<CR>" },
    { "<leader>g", group = " Git" },
    { "<leader>gA", desc = ":Gitsigns stage_buffer<CR>" },
    { "<leader>gB", desc = ":lua require('snacks').git.blame_line()<CR>" },
    { "<leader>gC", desc = ":CoAuthor<CR>" },
    { "<leader>gF", desc = ":Git<CR>" },
    { "<leader>gP", desc = ":Git push<CR>" },
    { "<leader>gR", desc = ":Gitsigns reset_buffer<CR>" },
    { "<leader>ga", desc = ":Gitsigns stage_hunk<CR>" },
    { "<leader>gb", desc = ":lua require('gitsigns').blame_line({full = true})<CR>" },
    { "<leader>gc", desc = ":Git commit<CR>" },
    { "<leader>gd", desc = ":Gitsigns diffthis HEAD<CR>" },
    { "<leader>gg", desc = ':lua require("snacks").lazygit()<CR>' },
    { "<leader>gi", desc = ":Gitsigns preview_hunk<CR>" },
    { "<leader>gj", desc = ":Gitsigns next_hunk<CR>" },
    { "<leader>gk", desc = ":Gitsigns prev_hunk<CR>" },
    { "<leader>gp", desc = ":Git pull<CR>" },
    { "<leader>gr", desc = ":Gitsigns reset_hunk<CR>" },
    { "<leader>gtb", desc = ":Gitsigns toggle_current_line_blame<CR>" },
    { "<leader>gtd", desc = ":Gitsigns toggle_deleted<CR>" },
    { "<leader>gtl", desc = ":Gitsigns toggle_linehl<CR>" },
    { "<leader>gtn", desc = ":Gitsigns toggle_numhl<CR>" },
    { "<leader>gts", desc = ":Gitsigns toggle_signs<CR>" },
    { "<leader>gtw", desc = ":Gitsigns toggle_word_diff<CR>" },
    { "<leader>gu", desc = ":Gitsigns undo_stage_hunk<CR>" },
    { "<leader>gv", desc = ":Gitsigns select_hunk<CR>" },
    { "<leader>gw", desc = ':lua require("snacks").gitbrowse()<CR>' },
    { "<leader>r", group = " Refactor" },
    { "<leader>ra", desc = ":lua require('spectre').open()<CR>" },
    { "<leader>rb", desc = ":lua require('spectre').open_file_search()<CR>" },
    { "<leader>rd", desc = ":lua vim.lsp.buf.definition()<CR>" },
    { "<leader>rh", desc = ':echo "List Definition Head"<CR>' },
    { "<leader>rj", desc = ':echo "Next Usage"<CR>' },
    { "<leader>rk", desc = ':echo "Previous Usage"<CR>' },
    { "<leader>rl", desc = ':echo "List Definition"<CR>' },
    { "<leader>rn", desc = ':echo "Swap Next"<CR>' },
    { "<leader>rp", desc = ':echo "Swap Previous"<CR>' },
    { "<leader>rr", desc = ":Lspsaga rename<CR>" },
    { "<leader>rw", desc = ":lua require('spectre').open_visual({select_word=true})<CR>" },
    { "<leader>x", desc = ":x<CR>" },
  }


